df0 <- data.frame(permutations(5,5, c('-','A','C','T','G'),repeats.allowed = T)) %>%
  dplyr::mutate(seq = paste0(X1,X2,X3,X4,X5)) %>%
  dplyr::rename(A = X1, B = X2, E = X3, C = X4, D = X5) %>%
  dplyr::mutate(muts = case_when((A == 'A' & B == 'A' & E=='A' & C =='A' & D == 'A') ~ 'No mutations',
                                 (A != 'A' & B == 'A' & E=='A' & C =='A' & D == 'A') ~ 'A site',
                                 (A == 'A' & B != 'A' & E=='A' & C =='A' & D == 'A') ~ 'B site',
                                 (A == 'A' & B == 'A' & E!='A' & C =='A' & D == 'A') ~ 'E site',
                                 (A == 'A' & B == 'A' & E=='A' & C !='A' & D == 'A') ~ 'C site',
                                 (A == 'A' & B == 'A' & E=='A' & C =='A' & D != 'A') ~ 'D site',
                                 (A != 'A' & B != 'A' & E=='A' & C =='A' & D == 'A') ~ 'AB site',
                                 (A != 'A' & B == 'A' & E !='A' & C =='A' & D == 'A') ~ 'AE site',
                                 (A != 'A' & B == 'A' & E=='A' & C !='A' & D == 'A') ~ 'AC site',
                                 (A != 'A' & B == 'A' & E=='A' & C =='A' & D != 'A') ~ 'AD site',
                                 (A == 'A' & B != 'A' & E!='A' & C =='A' & D == 'A') ~ 'BE site',
                                 (A == 'A' & B != 'A' & E=='A' & C !='A' & D == 'A') ~ 'BC site',
                                 (A == 'A' & B != 'A' & E=='A' & C =='A' & D != 'A') ~ 'BD site',
                                 (A == 'A' & B == 'A' & E!='A' & C !='A' & D == 'A') ~ 'EC site',
                                 (A == 'A' & B == 'A' & E!='A' & C =='A' & D != 'A') ~ 'ED site',
                                 (A == 'A' & B == 'A' & E =='A' & C !='A' & D != 'A') ~ 'CD site',
                                 (A != 'A' & B != 'A' & E !='A' & C == 'A' & D == 'A') ~ 'ABE site',
                                 (A != 'A' & B != 'A' & E =='A' & C != 'A' & D == 'A') ~ 'ABC site',
                                 (A != 'A' & B != 'A' & E =='A' & C == 'A' & D != 'A') ~ 'ABD site',
                                 (A != 'A' & B == 'A' & E !='A' & C != 'A' & D == 'A') ~ 'AEC site',
                                 (A != 'A' & B == 'A' & E !='A' & C == 'A' & D != 'A') ~ 'AED site',
                                 (A != 'A' & B == 'A' & E =='A' & C != 'A' & D != 'A') ~ 'ACD site',
                                 (A == 'A' & B != 'A' & E !='A' & C != 'A' & D == 'A') ~ 'BEC site',
                                 (A == 'A' & B != 'A' & E !='A' & C == 'A' & D != 'A') ~ 'BED site',
                                 (A == 'A' & B != 'A' & E =='A' & C != 'A' & D != 'A') ~ 'BCD site',
                                 (A == 'A' & B == 'A' & E !='A' & C != 'A' & D != 'A') ~ 'ECD site',
                                 (A != 'A' & B != 'A' & E !='A' & C != 'A' & D == 'A') ~ 'ABEC site',
                                 (A != 'A' & B != 'A' & E !='A' & C == 'A' & D != 'A') ~ 'ABED site',
                                 (A != 'A' & B != 'A' & E =='A' & C != 'A' & D != 'A') ~ 'ABCD site',
                                 (A != 'A' & B == 'A' & E !='A' & C != 'A' & D != 'A') ~ 'AECD site',
                                 (A == 'A' & B != 'A' & E !='A' & C != 'A' & D != 'A') ~ 'BECD site',
                                 (A != 'A' & B != 'A' & E !='A' & C != 'A' & D != 'A') ~ 'All mutated'))
df0 %>% vroom::vroom_write('~/ICEMaP/code/df0.txt')


df.A <- data.frame(permutations(5,5, c('-','A','C','T','G'),repeats.allowed = T)) %>%
  dplyr::mutate(seq = paste0(X1,X2,X3,X4,X5)) %>%
  dplyr::rename(A = X1, B = X2, E = X3, C = X4, D = X5) %>%
  dplyr::mutate(muts = case_when((A == 'G' & B == 'A' & E=='A' & C =='A' & D == 'A') ~ 'No mutations',
                                 (A != 'G' & B == 'A' & E=='A' & C =='A' & D == 'A') ~ 'A site',
                                 (A == 'G' & B != 'A' & E=='A' & C =='A' & D == 'A') ~ 'B site',
                                 (A == 'G' & B == 'A' & E!='A' & C =='A' & D == 'A') ~ 'E site',
                                 (A == 'G' & B == 'A' & E=='A' & C !='A' & D == 'A') ~ 'C site',
                                 (A == 'G' & B == 'A' & E=='A' & C =='A' & D != 'A') ~ 'D site',
                                 (A != 'G' & B != 'A' & E=='A' & C =='A' & D == 'A') ~ 'AB site',
                                 (A != 'G' & B == 'A' & E !='A' & C =='A' & D == 'A') ~ 'AE site',
                                 (A != 'G' & B == 'A' & E=='A' & C !='A' & D == 'A') ~ 'AC site',
                                 (A != 'G' & B == 'A' & E=='A' & C =='A' & D != 'A') ~ 'AD site',
                                 (A == 'G' & B != 'A' & E!='A' & C =='A' & D == 'A') ~ 'BE site',
                                 (A == 'G' & B != 'A' & E=='A' & C !='A' & D == 'A') ~ 'BC site',
                                 (A == 'G' & B != 'A' & E=='A' & C =='A' & D != 'A') ~ 'BD site',
                                 (A == 'G' & B == 'A' & E!='A' & C !='A' & D == 'A') ~ 'EC site',
                                 (A == 'G' & B == 'A' & E!='A' & C =='A' & D != 'A') ~ 'ED site',
                                 (A == 'G' & B == 'A' & E =='A' & C !='A' & D != 'A') ~ 'CD site',
                                 (A != 'G' & B != 'A' & E !='A' & C == 'A' & D == 'A') ~ 'ABE site',
                                 (A != 'G' & B != 'A' & E =='A' & C != 'A' & D == 'A') ~ 'ABC site',
                                 (A != 'G' & B != 'A' & E =='A' & C == 'A' & D != 'A') ~ 'ABD site',
                                 (A != 'G' & B == 'A' & E !='A' & C != 'A' & D == 'A') ~ 'AEC site',
                                 (A != 'G' & B == 'A' & E !='A' & C == 'A' & D != 'A') ~ 'AED site',
                                 (A != 'G' & B == 'A' & E =='A' & C != 'A' & D != 'A') ~ 'ACD site',
                                 (A == 'G' & B != 'A' & E !='A' & C != 'A' & D == 'A') ~ 'BEC site',
                                 (A == 'G' & B != 'A' & E !='A' & C == 'A' & D != 'A') ~ 'BED site',
                                 (A == 'G' & B != 'A' & E =='A' & C != 'A' & D != 'A') ~ 'BCD site',
                                 (A == 'G' & B == 'A' & E !='A' & C != 'A' & D != 'A') ~ 'ECD site',
                                 (A != 'G' & B != 'A' & E !='A' & C != 'A' & D == 'A') ~ 'ABEC site',
                                 (A != 'G' & B != 'A' & E !='A' & C == 'A' & D != 'A') ~ 'ABED site',
                                 (A != 'G' & B != 'A' & E =='A' & C != 'A' & D != 'A') ~ 'ABCD site',
                                 (A != 'G' & B == 'A' & E !='A' & C != 'A' & D != 'A') ~ 'AECD site',
                                 (A == 'G' & B != 'A' & E !='A' & C != 'A' & D != 'A') ~ 'BECD site',
                                 (A != 'G' & B != 'A' & E !='A' & C != 'A' & D != 'A') ~ 'All mutated'))
df.A %>% vroom::vroom_write('~/ICEMaP/code/dfA.txt')

dfB <- data.frame(permutations(5,5, c('-','A','C','T','G'),repeats.allowed = T)) %>%
  dplyr::mutate(seq = paste0(X1,X2,X3,X4,X5)) %>%
  dplyr::rename(A = X1, B = X2, E = X3, C = X4, D = X5) %>%
  dplyr::mutate(muts = case_when((A == 'A' & B == 'G' & E=='A' & C =='A' & D == 'A') ~ 'No mutations',
                                 (A != 'A' & B == 'G' & E=='A' & C =='A' & D == 'A') ~ 'A site',
                                 (A == 'A' & B != 'G' & E=='A' & C =='A' & D == 'A') ~ 'B site',
                                 (A == 'A' & B == 'G' & E!='A' & C =='A' & D == 'A') ~ 'E site',
                                 (A == 'A' & B == 'G' & E=='A' & C !='A' & D == 'A') ~ 'C site',
                                 (A == 'A' & B == 'G' & E=='A' & C =='A' & D != 'A') ~ 'D site',
                                 (A != 'A' & B != 'G' & E=='A' & C =='A' & D == 'A') ~ 'AB site',
                                 (A != 'A' & B == 'G' & E !='A' & C =='A' & D == 'A') ~ 'AE site',
                                 (A != 'A' & B == 'G' & E=='A' & C !='A' & D == 'A') ~ 'AC site',
                                 (A != 'A' & B == 'G' & E=='A' & C =='A' & D != 'A') ~ 'AD site',
                                 (A == 'A' & B != 'G' & E!='A' & C =='A' & D == 'A') ~ 'BE site',
                                 (A == 'A' & B != 'G' & E=='A' & C !='A' & D == 'A') ~ 'BC site',
                                 (A == 'A' & B != 'G' & E=='A' & C =='A' & D != 'A') ~ 'BD site',
                                 (A == 'A' & B == 'G' & E!='A' & C !='A' & D == 'A') ~ 'EC site',
                                 (A == 'A' & B == 'G' & E!='A' & C =='A' & D != 'A') ~ 'ED site',
                                 (A == 'A' & B == 'G' & E =='A' & C !='A' & D != 'A') ~ 'CD site',
                                 (A != 'A' & B != 'G' & E !='A' & C == 'A' & D == 'A') ~ 'ABE site',
                                 (A != 'A' & B != 'G' & E =='A' & C != 'A' & D == 'A') ~ 'ABC site',
                                 (A != 'A' & B != 'G' & E =='A' & C == 'A' & D != 'A') ~ 'ABD site',
                                 (A != 'A' & B == 'G' & E !='A' & C != 'A' & D == 'A') ~ 'AEC site',
                                 (A != 'A' & B == 'G' & E !='A' & C == 'A' & D != 'A') ~ 'AED site',
                                 (A != 'A' & B == 'G' & E =='A' & C != 'A' & D != 'A') ~ 'ACD site',
                                 (A == 'A' & B != 'G' & E !='A' & C != 'A' & D == 'A') ~ 'BEC site',
                                 (A == 'A' & B != 'G' & E !='A' & C == 'A' & D != 'A') ~ 'BED site',
                                 (A == 'A' & B != 'G' & E =='A' & C != 'A' & D != 'A') ~ 'BCD site',
                                 (A == 'A' & B == 'G' & E !='A' & C != 'A' & D != 'A') ~ 'ECD site',
                                 (A != 'A' & B != 'G' & E !='A' & C != 'A' & D == 'A') ~ 'ABEC site',
                                 (A != 'A' & B != 'G' & E !='A' & C == 'A' & D != 'A') ~ 'ABED site',
                                 (A != 'A' & B != 'G' & E =='A' & C != 'A' & D != 'A') ~ 'ABCD site',
                                 (A != 'A' & B == 'G' & E !='A' & C != 'A' & D != 'A') ~ 'AECD site',
                                 (A == 'A' & B != 'G' & E !='A' & C != 'A' & D != 'A') ~ 'BECD site',
                                 (A != 'A' & B != 'G' & E !='A' & C != 'A' & D != 'A') ~ 'All mutated'))
dfB %>% vroom::vroom_write('~/ICEMaP/code/dfB.txt')

df.AB <- data.frame(permutations(5,5, c('-','A','C','T','G'),repeats.allowed = T)) %>%
  dplyr::mutate(seq = paste0(X1,X2,X3,X4,X5)) %>%
  dplyr::rename(A = X1, B = X2, E = X3, C = X4, D = X5) %>%
  dplyr::mutate(muts = case_when((A == 'G' & B == 'G' & E=='A' & C =='A' & D == 'A') ~ 'No mutations',
                                 (A != 'G' & B == 'G' & E=='A' & C =='A' & D == 'A') ~ 'A site',
                                 (A == 'G' & B != 'G' & E=='A' & C =='A' & D == 'A') ~ 'B site',
                                 (A == 'G' & B == 'G' & E!='A' & C =='A' & D == 'A') ~ 'E site',
                                 (A == 'G' & B == 'G' & E=='A' & C !='A' & D == 'A') ~ 'C site',
                                 (A == 'G' & B == 'G' & E=='A' & C =='A' & D != 'A') ~ 'D site',
                                 (A != 'G' & B != 'G' & E=='A' & C =='A' & D == 'A') ~ 'AB site',
                                 (A != 'G' & B == 'G' & E !='A' & C =='A' & D == 'A') ~ 'AE site',
                                 (A != 'G' & B == 'G' & E=='A' & C !='A' & D == 'A') ~ 'AC site',
                                 (A != 'G' & B == 'G' & E=='A' & C =='A' & D != 'A') ~ 'AD site',
                                 (A == 'G' & B != 'G' & E!='A' & C =='A' & D == 'A') ~ 'BE site',
                                 (A == 'G' & B != 'G' & E=='A' & C !='A' & D == 'A') ~ 'BC site',
                                 (A == 'G' & B != 'G' & E=='A' & C =='A' & D != 'A') ~ 'BD site',
                                 (A == 'G' & B == 'G' & E!='A' & C !='A' & D == 'A') ~ 'EC site',
                                 (A == 'G' & B == 'G' & E!='A' & C =='A' & D != 'A') ~ 'ED site',
                                 (A == 'G' & B == 'G' & E =='A' & C !='A' & D != 'A') ~ 'CD site',
                                 (A != 'G' & B != 'G' & E !='A' & C == 'A' & D == 'A') ~ 'ABE site',
                                 (A != 'G' & B != 'G' & E =='A' & C != 'A' & D == 'A') ~ 'ABC site',
                                 (A != 'G' & B != 'G' & E =='A' & C == 'A' & D != 'A') ~ 'ABD site',
                                 (A != 'G' & B == 'G' & E !='A' & C != 'A' & D == 'A') ~ 'AEC site',
                                 (A != 'G' & B == 'G' & E !='A' & C == 'A' & D != 'A') ~ 'AED site',
                                 (A != 'G' & B == 'G' & E =='A' & C != 'A' & D != 'A') ~ 'ACD site',
                                 (A == 'G' & B != 'G' & E !='A' & C != 'A' & D == 'A') ~ 'BEC site',
                                 (A == 'G' & B != 'G' & E !='A' & C == 'A' & D != 'A') ~ 'BED site',
                                 (A == 'G' & B != 'G' & E =='A' & C != 'A' & D != 'A') ~ 'BCD site',
                                 (A == 'G' & B == 'G' & E !='A' & C != 'A' & D != 'A') ~ 'ECD site',
                                 (A != 'G' & B != 'G' & E !='A' & C != 'A' & D == 'A') ~ 'ABEC site',
                                 (A != 'G' & B != 'G' & E !='A' & C == 'A' & D != 'A') ~ 'ABED site',
                                 (A != 'G' & B != 'G' & E =='A' & C != 'A' & D != 'A') ~ 'ABCD site',
                                 (A != 'G' & B == 'G' & E !='A' & C != 'A' & D != 'A') ~ 'AECD site',
                                 (A == 'G' & B != 'G' & E !='A' & C != 'A' & D != 'A') ~ 'BECD site',
                                 (A != 'G' & B != 'G' & E !='A' & C != 'A' & D != 'A') ~ 'All mutated'))

df.AB %>% vroom::vroom_write('~/ICEMaP/code/dfAB.txt')

df.ABE <- data.frame(permutations(5,5, c('-','A','C','T','G'),repeats.allowed = T)) %>%
  dplyr::mutate(seq = paste0(X1,X2,X3,X4,X5)) %>%
  dplyr::rename(A = X1, B = X2, E = X3, C = X4, D = X5) %>%
  dplyr::mutate(muts = case_when((A == 'G' & B == 'G' & E=='G' & C =='A' & D == 'A') ~ 'No mutations',
                                 (A != 'G' & B == 'G' & E=='G' & C =='A' & D == 'A') ~ 'A site',
                                 (A == 'G' & B != 'G' & E=='G' & C =='A' & D == 'A') ~ 'B site',
                                 (A == 'G' & B == 'G' & E!='G' & C =='A' & D == 'A') ~ 'E site',
                                 (A == 'G' & B == 'G' & E=='G' & C !='A' & D == 'A') ~ 'C site',
                                 (A == 'G' & B == 'G' & E=='G' & C =='A' & D != 'A') ~ 'D site',
                                 (A != 'G' & B != 'G' & E=='G' & C =='A' & D == 'A') ~ 'AB site',
                                 (A != 'G' & B == 'G' & E !='G' & C =='A' & D == 'A') ~ 'AE site',
                                 (A != 'G' & B == 'G' & E=='G' & C !='A' & D == 'A') ~ 'AC site',
                                 (A != 'G' & B == 'G' & E=='G' & C =='A' & D != 'A') ~ 'AD site',
                                 (A == 'G' & B != 'G' & E!='G' & C =='A' & D == 'A') ~ 'BE site',
                                 (A == 'G' & B != 'G' & E=='G' & C !='A' & D == 'A') ~ 'BC site',
                                 (A == 'G' & B != 'G' & E=='G' & C =='A' & D != 'A') ~ 'BD site',
                                 (A == 'G' & B == 'G' & E!='G' & C !='A' & D == 'A') ~ 'EC site',
                                 (A == 'G' & B == 'G' & E!='G' & C =='A' & D != 'A') ~ 'ED site',
                                 (A == 'G' & B == 'G' & E =='G' & C !='A' & D != 'A') ~ 'CD site',
                                 (A != 'G' & B != 'G' & E !='G' & C == 'A' & D == 'A') ~ 'ABE site',
                                 (A != 'G' & B != 'G' & E =='G' & C != 'A' & D == 'A') ~ 'ABC site',
                                 (A != 'G' & B != 'G' & E =='G' & C == 'A' & D != 'A') ~ 'ABD site',
                                 (A != 'G' & B == 'G' & E !='G' & C != 'A' & D == 'A') ~ 'AEC site',
                                 (A != 'G' & B == 'G' & E !='G' & C == 'A' & D != 'A') ~ 'AED site',
                                 (A != 'G' & B == 'G' & E =='G' & C != 'A' & D != 'A') ~ 'ACD site',
                                 (A == 'G' & B != 'G' & E !='G' & C != 'A' & D == 'A') ~ 'BEC site',
                                 (A == 'G' & B != 'G' & E !='G' & C == 'A' & D != 'A') ~ 'BED site',
                                 (A == 'G' & B != 'G' & E =='G' & C != 'A' & D != 'A') ~ 'BCD site',
                                 (A == 'G' & B == 'G' & E !='G' & C != 'A' & D != 'A') ~ 'ECD site',
                                 (A != 'G' & B != 'G' & E !='G' & C != 'A' & D == 'A') ~ 'ABEC site',
                                 (A != 'G' & B != 'G' & E !='G' & C == 'A' & D != 'A') ~ 'ABED site',
                                 (A != 'G' & B != 'G' & E =='G' & C != 'A' & D != 'A') ~ 'ABCD site',
                                 (A != 'G' & B == 'G' & E !='G' & C != 'A' & D != 'A') ~ 'AECD site',
                                 (A == 'G' & B != 'G' & E !='G' & C != 'A' & D != 'A') ~ 'BECD site',
                                 (A != 'G' & B != 'G' & E !='G' & C != 'A' & D != 'A') ~ 'All mutated'))

df.ABE %>% vroom::vroom_write('~/ICEMaP/code/dfABE.txt')

df.ABC <- data.frame(permutations(5,5, c('-','A','C','T','G'),repeats.allowed = T)) %>%
  dplyr::mutate(seq = paste0(X1,X2,X3,X4,X5)) %>%
  dplyr::rename(A = X1, B = X2, E = X3, C = X4, D = X5) %>%
  dplyr::mutate(muts = case_when((A == 'G' & B == 'G' & E=='A' & C =='G' & D == 'A') ~ 'No mutations',
                                 (A != 'G' & B == 'G' & E=='A' & C =='G' & D == 'A') ~ 'A site',
                                 (A == 'G' & B != 'G' & E=='A' & C =='G' & D == 'A') ~ 'B site',
                                 (A == 'G' & B == 'G' & E!='A' & C =='G' & D == 'A') ~ 'E site',
                                 (A == 'G' & B == 'G' & E=='A' & C !='G' & D == 'A') ~ 'C site',
                                 (A == 'G' & B == 'G' & E=='A' & C =='G' & D != 'A') ~ 'D site',
                                 (A != 'G' & B != 'G' & E=='A' & C =='G' & D == 'A') ~ 'AB site',
                                 (A != 'G' & B == 'G' & E !='A' & C =='G' & D == 'A') ~ 'AE site',
                                 (A != 'G' & B == 'G' & E=='A' & C !='G' & D == 'A') ~ 'AC site',
                                 (A != 'G' & B == 'G' & E=='A' & C =='G' & D != 'A') ~ 'AD site',
                                 (A == 'G' & B != 'G' & E!='A' & C =='G' & D == 'A') ~ 'BE site',
                                 (A == 'G' & B != 'G' & E=='A' & C !='G' & D == 'A') ~ 'BC site',
                                 (A == 'G' & B != 'G' & E=='A' & C =='G' & D != 'A') ~ 'BD site',
                                 (A == 'G' & B == 'G' & E!='A' & C !='G' & D == 'A') ~ 'EC site',
                                 (A == 'G' & B == 'G' & E!='A' & C =='G' & D != 'A') ~ 'ED site',
                                 (A == 'G' & B == 'G' & E =='A' & C !='G' & D != 'A') ~ 'CD site',
                                 (A != 'G' & B != 'G' & E !='A' & C == 'G' & D == 'A') ~ 'ABE site',
                                 (A != 'G' & B != 'G' & E =='A' & C != 'G' & D == 'A') ~ 'ABC site',
                                 (A != 'G' & B != 'G' & E =='A' & C == 'G' & D != 'A') ~ 'ABD site',
                                 (A != 'G' & B == 'G' & E !='A' & C != 'G' & D == 'A') ~ 'AEC site',
                                 (A != 'G' & B == 'G' & E !='A' & C == 'G' & D != 'A') ~ 'AED site',
                                 (A != 'G' & B == 'G' & E =='A' & C != 'G' & D != 'A') ~ 'ACD site',
                                 (A == 'G' & B != 'G' & E !='A' & C != 'G' & D == 'A') ~ 'BEC site',
                                 (A == 'G' & B != 'G' & E !='A' & C == 'G' & D != 'A') ~ 'BED site',
                                 (A == 'G' & B != 'G' & E =='A' & C != 'G' & D != 'A') ~ 'BCD site',
                                 (A == 'G' & B == 'G' & E !='A' & C != 'G' & D != 'A') ~ 'ECD site',
                                 (A != 'G' & B != 'G' & E !='A' & C != 'G' & D == 'A') ~ 'ABEC site',
                                 (A != 'G' & B != 'G' & E !='A' & C == 'G' & D != 'A') ~ 'ABED site',
                                 (A != 'G' & B != 'G' & E =='A' & C != 'G' & D != 'A') ~ 'ABCD site',
                                 (A != 'G' & B == 'G' & E !='A' & C != 'G' & D != 'A') ~ 'AECD site',
                                 (A == 'G' & B != 'G' & E !='A' & C != 'G' & D != 'A') ~ 'BECD site',
                                 (A != 'G' & B != 'G' & E !='A' & C != 'G' & D != 'A') ~ 'All mutated'))

df.ABC %>% vroom::vroom_write('~/ICEMaP/code/dfABC.txt')

df.ABECD <- data.frame(permutations(5,5, c('-','A','C','T','G'),repeats.allowed = T)) %>%
  dplyr::mutate(seq = paste0(X1,X2,X3,X4,X5)) %>%
  dplyr::rename(A = X1, B = X2, E = X3, C = X4, D = X5) %>%
  dplyr::mutate(muts = case_when((A == 'G' & B == 'G' & E=='G' & C =='G' & D == 'G') ~ 'No mutations',
                                 (A != 'G' & B == 'G' & E=='G' & C =='G' & D == 'G') ~ 'A site',
                                 (A == 'G' & B != 'G' & E=='G' & C =='G' & D == 'G') ~ 'B site',
                                 (A == 'G' & B == 'G' & E!='G' & C =='G' & D == 'G') ~ 'E site',
                                 (A == 'G' & B == 'G' & E=='G' & C !='G' & D == 'G') ~ 'C site',
                                 (A == 'G' & B == 'G' & E=='G' & C =='G' & D != 'G') ~ 'D site',
                                 (A != 'G' & B != 'G' & E=='G' & C =='G' & D == 'G') ~ 'AB site',
                                 (A != 'G' & B == 'G' & E !='G' & C =='G' & D == 'G') ~ 'AE site',
                                 (A != 'G' & B == 'G' & E=='G' & C !='G' & D == 'G') ~ 'AC site',
                                 (A != 'G' & B == 'G' & E=='G' & C =='G' & D != 'G') ~ 'AD site',
                                 (A == 'G' & B != 'G' & E!='G' & C =='G' & D == 'G') ~ 'BE site',
                                 (A == 'G' & B != 'G' & E=='G' & C !='G' & D == 'G') ~ 'BC site',
                                 (A == 'G' & B != 'G' & E=='G' & C =='G' & D != 'G') ~ 'BD site',
                                 (A == 'G' & B == 'G' & E!='G' & C !='G' & D == 'G') ~ 'EC site',
                                 (A == 'G' & B == 'G' & E!='G' & C =='G' & D != 'G') ~ 'ED site',
                                 (A == 'G' & B == 'G' & E =='G' & C !='G' & D != 'G') ~ 'CD site',
                                 (A != 'G' & B != 'G' & E !='G' & C == 'G' & D == 'G') ~ 'ABE site',
                                 (A != 'G' & B != 'G' & E =='G' & C != 'G' & D == 'G') ~ 'ABC site',
                                 (A != 'G' & B != 'G' & E =='G' & C == 'G' & D != 'G') ~ 'ABD site',
                                 (A != 'G' & B == 'G' & E !='G' & C != 'G' & D == 'G') ~ 'AEC site',
                                 (A != 'G' & B == 'G' & E !='G' & C == 'G' & D != 'G') ~ 'AED site',
                                 (A != 'G' & B == 'G' & E =='G' & C != 'G' & D != 'G') ~ 'ACD site',
                                 (A == 'G' & B != 'G' & E !='G' & C != 'G' & D == 'G') ~ 'BEC site',
                                 (A == 'G' & B != 'G' & E !='G' & C == 'G' & D != 'G') ~ 'BED site',
                                 (A == 'G' & B != 'G' & E =='G' & C != 'G' & D != 'G') ~ 'BCD site',
                                 (A == 'G' & B == 'G' & E !='G' & C != 'G' & D != 'G') ~ 'ECD site',
                                 (A != 'G' & B != 'G' & E !='G' & C != 'G' & D == 'G') ~ 'ABEC site',
                                 (A != 'G' & B != 'G' & E !='G' & C == 'G' & D != 'G') ~ 'ABED site',
                                 (A != 'G' & B != 'G' & E =='G' & C != 'G' & D != 'G') ~ 'ABCD site',
                                 (A != 'G' & B == 'G' & E !='G' & C != 'G' & D != 'G') ~ 'AECD site',
                                 (A == 'G' & B != 'G' & E !='G' & C != 'G' & D != 'G') ~ 'BECD site',
                                 (A != 'G' & B != 'G' & E !='G' & C != 'G' & D != 'G') ~ 'All mutated'))

df.ABECD %>% vroom::vroom_write('~/ICEMaP/code/dfABECD.txt')
